# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{russian}
  s.version = "0.2.8.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yaroslav Markin"]
  s.date = %q{2010-12-20}
  s.description = %q{Russian language support for Ruby and Rails}
  s.email = %q{yaroslav@markin.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "TODO",
    "init.rb",
    "lib/russian.rb",
    "lib/russian/action_view_ext/helpers/date_helper.rb",
    "lib/russian/active_support_ext/parameterize.rb",
    "lib/russian/backend/advanced.rb",
    "lib/russian/locale/actionview.yml",
    "lib/russian/locale/activemodel.yml",
    "lib/russian/locale/activerecord.yml",
    "lib/russian/locale/activesupport.yml",
    "lib/russian/locale/datetime.yml",
    "lib/russian/locale/pluralize.rb",
    "lib/russian/transliteration.rb",
    "lib/vendor/i18n/.gitignore",
    "lib/vendor/i18n/MIT-LICENSE",
    "lib/vendor/i18n/README.textile",
    "lib/vendor/i18n/Rakefile",
    "lib/vendor/i18n/i18n.gemspec",
    "lib/vendor/i18n/lib/i18n.rb",
    "lib/vendor/i18n/lib/i18n/backend/simple.rb",
    "lib/vendor/i18n/lib/i18n/exceptions.rb",
    "lib/vendor/i18n/test/all.rb",
    "lib/vendor/i18n/test/i18n_exceptions_test.rb",
    "lib/vendor/i18n/test/i18n_test.rb",
    "lib/vendor/i18n/test/locale/en.rb",
    "lib/vendor/i18n/test/locale/en.yml",
    "lib/vendor/i18n/test/simple_backend_test.rb",
    "russian.gemspec",
    "spec/fixtures/en.yml",
    "spec/fixtures/ru.yml",
    "spec/i18n/locale/datetime_spec.rb",
    "spec/i18n/locale/pluralization_spec.rb",
    "spec/locale_spec.rb",
    "spec/russian_spec.rb",
    "spec/spec_helper.rb",
    "spec/transliteration_spec.rb"
  ]
  s.homepage = %q{http://github.com/yaroslav/russian/}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Russian language support for Ruby and Rails}
  s.test_files = [
    "spec/i18n/locale/datetime_spec.rb",
    "spec/i18n/locale/pluralization_spec.rb",
    "spec/locale_spec.rb",
    "spec/russian_spec.rb",
    "spec/spec_helper.rb",
    "spec/transliteration_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, ["~> 0.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<i18n>, ["~> 0.4"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<i18n>, ["~> 0.4"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

